basePath: /
host: localhost:8000
info:
  contact: {}
  description: This is a sample server.
  title: My apu
  version: "1.0"
paths:
  /result/{id}:
    get:
      description: returns result_status by task id
      parameters:
      - description: Key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: Value
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: get result_value
  /status/{id}:
    get:
      description: returns value_status by task id
      parameters:
      - description: Key
        in: query
        name: key
        required: true
        type: string
      responses:
        "200":
          description: Value
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: get status_value
  /task:
    get:
      description: Creating new id for the task and returning
      responses:
        "200":
          description: Value
          schema:
            type: data
      summary: Creating new id for the task
swagger: "2.0"
